package com.swifta.sub.mats.operation.financial.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-10T13:22:08.263+01:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", name = "Financial")
@XmlSeeAlso({com.swifta.sub.mats.operation.financial.v1.ObjectFactory.class})
public interface Financial {

    @WebMethod
    @RequestWrapper(localName = "getaccounttransactionhistoryrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Getaccounttransactionhistoryrequest")
    @ResponseWrapper(localName = "getaccounttransactionhistoryrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.GetaccounttransactionhistoryrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Getaccounttransactionhistoryresponse getaccounttransactionhistoryrequest(
        @WebParam(name = "accountresource", targetNamespace = "")
        java.lang.String accountresource,
        @WebParam(name = "otheraccountresource", targetNamespace = "")
        java.lang.String otheraccountresource,
        @WebParam(name = "fromdate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fromdate,
        @WebParam(name = "todate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar todate,
        @WebParam(name = "nooftransactionhistory", targetNamespace = "")
        java.lang.String nooftransactionhistory,
        @WebParam(name = "transactionid", targetNamespace = "")
        java.lang.String transactionid,
        @WebParam(name = "transactionentrytype", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.EntryType transactionentrytype,
        @WebParam(name = "operationtype", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.OperationType operationtype
    );

    @WebMethod
    @RequestWrapper(localName = "cashoutrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Cashoutrequest")
    @ResponseWrapper(localName = "cashoutrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.CashoutrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Cashoutresponse cashoutrequest(
        @WebParam(name = "orginatingresourceid", targetNamespace = "")
        java.lang.String orginatingresourceid,
        @WebParam(name = "destinationresourceid", targetNamespace = "")
        java.lang.String destinationresourceid,
        @WebParam(name = "amount", targetNamespace = "")
        java.lang.String amount,
        @WebParam(name = "sendingdescription", targetNamespace = "")
        java.lang.String sendingdescription,
        @WebParam(name = "receivingdescription", targetNamespace = "")
        java.lang.String receivingdescription,
        @WebParam(name = "extensionparameters", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.ParameterExtension extensionparameters
    );

    @WebMethod
    @RequestWrapper(localName = "gettransactionhistoryrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Gettransactionhistoryrequest")
    @ResponseWrapper(localName = "gettransactionhistoryrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.GettransactionhistoryrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Gettransactionhistoryresponse gettransactionhistoryrequest(
        @WebParam(name = "transactionhistoryparameter", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.Gettransactionhistoryparameter transactionhistoryparameter
    );

    @WebMethod
    @RequestWrapper(localName = "transfertobankaccountrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Transfertobankaccountrequest")
    @ResponseWrapper(localName = "transfertobankaccountrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.TransfertobankaccountrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Transfertobankrequestresponse transfertobankaccountrequest(
        @WebParam(name = "userresourceid", targetNamespace = "")
        java.lang.String userresourceid,
        @WebParam(name = "accountresourceid", targetNamespace = "")
        java.lang.String accountresourceid,
        @WebParam(name = "amount", targetNamespace = "")
        java.lang.String amount,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "bankcode", targetNamespace = "")
        java.lang.String bankcode,
        @WebParam(name = "bankaccountnumber", targetNamespace = "")
        java.lang.String bankaccountnumber,
        @WebParam(name = "extension", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.ParameterExtension extension
    );

    @WebMethod
    @RequestWrapper(localName = "floattransferrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Floattransferrequest")
    @ResponseWrapper(localName = "floattransferrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.FloattransferrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Floattransferresponse floattransferrequest(
        @WebParam(name = "orginatingresourceid", targetNamespace = "")
        java.lang.String orginatingresourceid,
        @WebParam(name = "destinationresourceid", targetNamespace = "")
        java.lang.String destinationresourceid,
        @WebParam(name = "amount", targetNamespace = "")
        java.lang.String amount,
        @WebParam(name = "sendingdescription", targetNamespace = "")
        java.lang.String sendingdescription,
        @WebParam(name = "receivingdescription", targetNamespace = "")
        java.lang.String receivingdescription,
        @WebParam(name = "extension", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.ParameterExtension extension
    );

    @WebMethod
    @RequestWrapper(localName = "cashinrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Cashinrequest")
    @ResponseWrapper(localName = "cashinrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.CashinrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Cashinresponse cashinrequest(
        @WebParam(name = "orginatingresourceid", targetNamespace = "")
        java.lang.String orginatingresourceid,
        @WebParam(name = "destinationresourceid", targetNamespace = "")
        java.lang.String destinationresourceid,
        @WebParam(name = "amount", targetNamespace = "")
        java.lang.String amount,
        @WebParam(name = "sendingdescription", targetNamespace = "")
        java.lang.String sendingdescription,
        @WebParam(name = "receivingdescription", targetNamespace = "")
        java.lang.String receivingdescription,
        @WebParam(name = "extensionparameters", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.ParameterExtension extensionparameters
    );

    @WebMethod
    @RequestWrapper(localName = "adjustaccountrequest", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.Adjustaccountrequest")
    @ResponseWrapper(localName = "adjustaccountrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0", className = "com.swifta.sub.mats.operation.financial.v1.AdjustaccountrequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.swifta.sub.mats.operation.financial.v1.Adjustaccountresponse adjustaccountrequest(
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "adjustaccountinstruction", targetNamespace = "")
        com.swifta.sub.mats.operation.financial.v1.Adjustaccounttransactionparameters adjustaccountinstruction
    );
}
