package com.swifta.sub.mats.operation.financial.v1_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-15T17:44:55.170+01:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "financials", 
                  wsdlLocation = "/Users/user/Documents/swifta/Financial/src/main/webapp/WEB-INF/wsdl/Financial.wsdl",
                  targetNamespace = "http://swifta.com/sub/mats/operation/financial/v1.0") 
public class Financials extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://swifta.com/sub/mats/operation/financial/v1.0", "financials");
    public final static QName FinancialPort = new QName("http://swifta.com/sub/mats/operation/financial/v1.0", "FinancialPort");
    static {
        URL url = Financials.class.getResource("/Users/user/Documents/swifta/Financial/src/main/webapp/WEB-INF/wsdl/Financial.wsdl");
        if (url == null) {
            url = Financials.class.getClassLoader().getResource("/Users/user/Documents/swifta/Financial/src/main/webapp/WEB-INF/wsdl/Financial.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(Financials.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/user/Documents/swifta/Financial/src/main/webapp/WEB-INF/wsdl/Financial.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Financials(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Financials(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Financials() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Financials(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Financials(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Financials(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Financial
     */
    @WebEndpoint(name = "FinancialPort")
    public Financial getFinancialPort() {
        return super.getPort(FinancialPort, Financial.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Financial
     */
    @WebEndpoint(name = "FinancialPort")
    public Financial getFinancialPort(WebServiceFeature... features) {
        return super.getPort(FinancialPort, Financial.class, features);
    }

}
